name: "CI - Nix"

on:
  push:
    paths-ignore:
      - .gitlab-ci.yml
      - .gitignore
      - '*.md'
      - CITATION.*
      - LICENSE
      - colcon.pkg
      - .pre-commit-config.yaml
      - CHANGELOG.md
      - development/*.md
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix:
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      matrix:
        os: [ubuntu, macos]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v15
        with:
          name: gepetto
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L
